name: Discord Messager Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build