name: Discord Messages Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages
      run: npm ci
    - name: Build the Application
      run: npm run build --if-present
    - name: Test the Application
      run: npm test --if-present
    - name: Restart the Application on EC2
      run: pm2 restart ecosystem.config.js
