name: Discord Messages Pipeline Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          TARGET: ${{ secrets.EC2_APP_DIR }}
          EXCLUDE: "/build/, /node_modules/"
  post-deploy:
    runs-on: self-hosted
    steps:
      - name: Install packages
        run: cd ${{ secrets.EC2_APP_DIR }} && yarn
      - name: Build the Application
        run: cd ${{ secrets.EC2_APP_DIR }} && yarn build
      - name: Restart the Application
        run: cd ${{ secrets.EC2_APP_DIR }} && pm2 restart ecosystem.config.js