name: Discord Messages Pipeline Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          TARGET: ${{ secrets.EC2_APP_DIR }}
          EXCLUDE: "/build/, /node_modules/"
      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ${{ secrets.EC2_APP_DIR }};
            yarn;
            yarn build;
            pm2 restart ecosystem.config.js;