name: Discord Messages Pipeline Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ secrets.EC2_APP_DIR }}
    steps:
      - name: Pull code
        run: git pull
      - name: Install packages
        run: yarn
      - name: Build the Application
        run: yarn build
      - name: Restart the Application
        run: pm2 restart ecosystem.config.js