name: Discord Messages Pipeline Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull code
        run: cd ${{ secrets.EC2_APP_DIR }} && git pull
      - name: Install packages
        run: cd ${{ secrets.EC2_APP_DIR }} && yarn
      - name: Build the Application
        run: cd ${{ secrets.EC2_APP_DIR }} && yarn build
      - name: Restart the Application
        run: cd ${{ secrets.EC2_APP_DIR }} && pm2 resta146.190.204.185rt ecosystem.config.js